### ISSUE TITLE
Parse all user vods and sync

### ISSUE THREAD

**Issue by Codewyvern** [LordH3lmchen/TwitchDownloader#1]
I use TwitchTools a lot just to save vods before they are deleted, the only issue I have is that I have to manually copy and paste each vod from a channel into a separate instance of TwitchTools. It would be great if I could simply copy and paste the users vod page link into the application, it would enumerate all the vods and tell me what needs to be updated (kind of like syncing the vods to my computer). I am not sure if the vod download has checksums/hashes but that way it would be very quick and easy for a person to download their favorite vods.

**Comment by LordH3lmchen** [comment]
nice idea, for that purpose i would recomend to write a small script (python, bash ...)

I want to implement a commandline interface for TwitchTools. This schould allow everyone to use TwitchTools in scripts.

You mean that page right?
http://www.twitch.tv/lowkotv/profile/past_broadcasts
Theres a way to get a VOD-List
https://api.twitch.tv/kraken/channels/lowkotv/videos?broadcasts=true

https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md

without the broadcast option it returns the highlights

The URL to the video (like http://www.twitch.tv/lowkotv/b/608227427) is unique, should be posible to write a sync tool.

**Comment by LordH3lmchen** [comment]
I've made some changes. the tool is able to sync channels now.

**Comment by Codewyvern** [comment]
Awesome :)
