### ISSUE TITLE
Feature: CLI 

### ISSUE THREAD

**Issue by fionera** [LordH3lmchen/TwitchDownloader#8]
Hi,

it would be awesome to have a CLI :)

**Comment by LordH3lmchen** [comment]
There is a tool called youtube-dl. That I use all the time. This Project was just for me to learn Java (Swing).

youtube-dl is well maintained and a lot better than my Java Tool.

https://github.com/rg3/youtube-dl
https://pypi.org/project/youtube_dl/

I run this on my phone (Android, via an app called "termux" - use F-Droid to download it), on Windows, and mainly on Linux. 

Just use pip to install it.

`pip install youtube_dl`
